name: Audit

on:
  push:
  workflow_dispatch:

jobs:
  Audit:
    name: Audit
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Audit code
        run: yarn audit